local yak_air_zone = RAT:New("RAT_YAK_AIR","RAT_YAK_AIR_ZONE")
    :SetTakeoff("air")
    :SetDeparture({"RAT_AIR_SPAWN"})
    :Livery({"Georgian Airlines","Olympic Airways (Vintage)","Algerian Gouverment GLAM","Ukranian","Aeroflot"})
    :ATC_Messages(false)
    :RadioOFF()

local yak_air_ap = RAT:New("RAT_YAK_AIR","RAT_YAK_AIR_AP")
    :SetTakeoff("air")
    :Livery({"Georgian Airlines","Olympic Airways (Vintage)","Algerian Gouverment GLAM","Ukranian","Aeroflot"})
    :ATC_Messages(false)
    :RadioOFF()

local yak_gnd = RAT:New("RAT_YAK_GND")
    :ATC_Messages(false)
    :RadioOFF()

local ce_air = RAT:New("RAT_CE_AIR")
    :SetTakeoff("air")
    :Livery({"C-FTIJ","G-KLAW","N22XS"})
    :ATC_Messages(false)
    :RadioOFF()


local tgt_cargo_1 = RAT:New("RAT_TGT_AIR","RAT_Transport_1")
    :SetDeparture({"RAT_TGT_SPAWN_1"})
    :SetDestination({"RAT_TGT_DEST"})
    :Livery({"RF Air Force"})
    :SetROT("evade")
    :ATC_Messages(false)
    :RadioOFF()    

local tgt_cargo_2 = RAT:New("RAT_TGT_AIR","RAT_Transport_2")
    :SetDeparture({"RAT_TGT_SPAWN_2"})
    :SetDestination({"RAT_TGT_DEST"})
    :Livery({"RF Air Force"})
    :SetROT("evade")
    :ATC_Messages(false)
    :RadioOFF()

local tgt_cargo_3 = RAT:New("RAT_TGT_AIR","RAT_Transport_3")
    :SetDeparture({"RAT_TGT_SPAWN_3"})
    :SetDestination({"RAT_TGT_DEST"})
    :Livery({"RF Air Force"})
    :SetROT("evade")
    :ATC_Messages(false)
    :RadioOFF()

local rat_manager = RATMANAGER:New(73)
    :Add(yak_air_ap, 10)
    :Add(yak_air_zone, 20)
    :Add(yak_gnd,20)
    :Add(ce_air,20)
    :Add(tgt_cargo_1,1)
    :Add(tgt_cargo_2,1)
    :Add(tgt_cargo_3,1)
    :Start(10)

rat_manager:Stop(120)